// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: api/media/v1/media.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUploadURLRequest_MediaType int32

const (
	GetUploadURLRequest_UNKNOWN GetUploadURLRequest_MediaType = 0
	GetUploadURLRequest_Avatar  GetUploadURLRequest_MediaType = 1
	GetUploadURLRequest_Image   GetUploadURLRequest_MediaType = 2
	GetUploadURLRequest_Video   GetUploadURLRequest_MediaType = 3
	GetUploadURLRequest_Audio   GetUploadURLRequest_MediaType = 4
)

// Enum value maps for GetUploadURLRequest_MediaType.
var (
	GetUploadURLRequest_MediaType_name = map[int32]string{
		0: "UNKNOWN",
		1: "Avatar",
		2: "Image",
		3: "Video",
		4: "Audio",
	}
	GetUploadURLRequest_MediaType_value = map[string]int32{
		"UNKNOWN": 0,
		"Avatar":  1,
		"Image":   2,
		"Video":   3,
		"Audio":   4,
	}
)

func (x GetUploadURLRequest_MediaType) Enum() *GetUploadURLRequest_MediaType {
	p := new(GetUploadURLRequest_MediaType)
	*p = x
	return p
}

func (x GetUploadURLRequest_MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUploadURLRequest_MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_media_v1_media_proto_enumTypes[0].Descriptor()
}

func (GetUploadURLRequest_MediaType) Type() protoreflect.EnumType {
	return &file_api_media_v1_media_proto_enumTypes[0]
}

func (x GetUploadURLRequest_MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUploadURLRequest_MediaType.Descriptor instead.
func (GetUploadURLRequest_MediaType) EnumDescriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{0, 0}
}

type GetUploadURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of media to upload
	MediaType GetUploadURLRequest_MediaType `protobuf:"varint,1,opt,name=media_type,json=mediaType,proto3,enum=mealeyau.api.media.v1.GetUploadURLRequest_MediaType" json:"media_type,omitempty"`
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_media_v1_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetUploadURLRequest) GetMediaType() GetUploadURLRequest_MediaType {
	if x != nil {
		return x.MediaType
	}
	return GetUploadURLRequest_UNKNOWN
}

type GetUploadURLResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetUploadURLResult) Reset() {
	*x = GetUploadURLResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_media_v1_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUploadURLResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResult) ProtoMessage() {}

func (x *GetUploadURLResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResult.ProtoReflect.Descriptor instead.
func (*GetUploadURLResult) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetUploadURLResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUploadURLResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_media_v1_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetDownloadURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDownloadURLResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetDownloadURLResult) Reset() {
	*x = GetDownloadURLResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_media_v1_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDownloadURLResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResult) ProtoMessage() {}

func (x *GetDownloadURLResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResult.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResult) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetDownloadURLResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_api_media_v1_media_proto protoreflect.FileDescriptor

var file_api_media_v1_media_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x65, 0x61, 0x6c,
	0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x22, 0xb1, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x0a, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e,
	0x6d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x45,
	0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x10, 0x04, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x27, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0xe2, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x65, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52,
	0x4c, 0x12, 0x2a, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e,
	0x6d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x52, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x6b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x2c, 0x2e, 0x6d, 0x65, 0x61,
	0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x65,
	0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x41, 0x55, 0x2f, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_media_v1_media_proto_rawDescOnce sync.Once
	file_api_media_v1_media_proto_rawDescData = file_api_media_v1_media_proto_rawDesc
)

func file_api_media_v1_media_proto_rawDescGZIP() []byte {
	file_api_media_v1_media_proto_rawDescOnce.Do(func() {
		file_api_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_media_v1_media_proto_rawDescData)
	})
	return file_api_media_v1_media_proto_rawDescData
}

var file_api_media_v1_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_media_v1_media_proto_goTypes = []interface{}{
	(GetUploadURLRequest_MediaType)(0), // 0: mealeyau.api.media.v1.GetUploadURLRequest.MediaType
	(*GetUploadURLRequest)(nil),        // 1: mealeyau.api.media.v1.GetUploadURLRequest
	(*GetUploadURLResult)(nil),         // 2: mealeyau.api.media.v1.GetUploadURLResult
	(*GetDownloadURLRequest)(nil),      // 3: mealeyau.api.media.v1.GetDownloadURLRequest
	(*GetDownloadURLResult)(nil),       // 4: mealeyau.api.media.v1.GetDownloadURLResult
}
var file_api_media_v1_media_proto_depIdxs = []int32{
	0, // 0: mealeyau.api.media.v1.GetUploadURLRequest.media_type:type_name -> mealeyau.api.media.v1.GetUploadURLRequest.MediaType
	1, // 1: mealeyau.api.media.v1.MediaService.GetUploadURL:input_type -> mealeyau.api.media.v1.GetUploadURLRequest
	3, // 2: mealeyau.api.media.v1.MediaService.GetDownloadURL:input_type -> mealeyau.api.media.v1.GetDownloadURLRequest
	2, // 3: mealeyau.api.media.v1.MediaService.GetUploadURL:output_type -> mealeyau.api.media.v1.GetUploadURLResult
	4, // 4: mealeyau.api.media.v1.MediaService.GetDownloadURL:output_type -> mealeyau.api.media.v1.GetDownloadURLResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_media_v1_media_proto_init() }
func file_api_media_v1_media_proto_init() {
	if File_api_media_v1_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_media_v1_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUploadURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_media_v1_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUploadURLResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_media_v1_media_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDownloadURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_media_v1_media_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDownloadURLResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_media_v1_media_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_media_v1_media_proto_goTypes,
		DependencyIndexes: file_api_media_v1_media_proto_depIdxs,
		EnumInfos:         file_api_media_v1_media_proto_enumTypes,
		MessageInfos:      file_api_media_v1_media_proto_msgTypes,
	}.Build()
	File_api_media_v1_media_proto = out.File
	file_api_media_v1_media_proto_rawDesc = nil
	file_api_media_v1_media_proto_goTypes = nil
	file_api_media_v1_media_proto_depIdxs = nil
}
