// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: api/authentication/admin/v1/authentication.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPasswordCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AddPasswordCredentialsRequest) Reset() {
	*x = AddPasswordCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_admin_v1_authentication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPasswordCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPasswordCredentialsRequest) ProtoMessage() {}

func (x *AddPasswordCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_admin_v1_authentication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPasswordCredentialsRequest.ProtoReflect.Descriptor instead.
func (*AddPasswordCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_authentication_admin_v1_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *AddPasswordCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPasswordCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddPasswordCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AddPasswordCredentialsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPasswordCredentialsResult) Reset() {
	*x = AddPasswordCredentialsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_admin_v1_authentication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPasswordCredentialsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPasswordCredentialsResult) ProtoMessage() {}

func (x *AddPasswordCredentialsResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_admin_v1_authentication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPasswordCredentialsResult.ProtoReflect.Descriptor instead.
func (*AddPasswordCredentialsResult) Descriptor() ([]byte, []int) {
	return file_api_authentication_admin_v1_authentication_proto_rawDescGZIP(), []int{1}
}

var File_api_authentication_admin_v1_authentication_proto protoreflect.FileDescriptor

var file_api_authentication_admin_v1_authentication_proto_rawDesc = []byte{
	0x0a, 0x30, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x24, 0x6d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x6a, 0x0a, 0x1d, 0x41, 0x64, 0x64, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0xc0, 0x01, 0x0a, 0x1a, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0xa1, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x43,
	0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x42, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x61, 0x75, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x61, 0x6c, 0x65, 0x79, 0x41, 0x55, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_authentication_admin_v1_authentication_proto_rawDescOnce sync.Once
	file_api_authentication_admin_v1_authentication_proto_rawDescData = file_api_authentication_admin_v1_authentication_proto_rawDesc
)

func file_api_authentication_admin_v1_authentication_proto_rawDescGZIP() []byte {
	file_api_authentication_admin_v1_authentication_proto_rawDescOnce.Do(func() {
		file_api_authentication_admin_v1_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_authentication_admin_v1_authentication_proto_rawDescData)
	})
	return file_api_authentication_admin_v1_authentication_proto_rawDescData
}

var file_api_authentication_admin_v1_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_authentication_admin_v1_authentication_proto_goTypes = []interface{}{
	(*AddPasswordCredentialsRequest)(nil), // 0: mealeyau.api.authentication.admin.v1.AddPasswordCredentialsRequest
	(*AddPasswordCredentialsResult)(nil),  // 1: mealeyau.api.authentication.admin.v1.AddPasswordCredentialsResult
}
var file_api_authentication_admin_v1_authentication_proto_depIdxs = []int32{
	0, // 0: mealeyau.api.authentication.admin.v1.AdminAuthenticationService.AddPasswordCredentials:input_type -> mealeyau.api.authentication.admin.v1.AddPasswordCredentialsRequest
	1, // 1: mealeyau.api.authentication.admin.v1.AdminAuthenticationService.AddPasswordCredentials:output_type -> mealeyau.api.authentication.admin.v1.AddPasswordCredentialsResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_authentication_admin_v1_authentication_proto_init() }
func file_api_authentication_admin_v1_authentication_proto_init() {
	if File_api_authentication_admin_v1_authentication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_authentication_admin_v1_authentication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPasswordCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_admin_v1_authentication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPasswordCredentialsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_authentication_admin_v1_authentication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_authentication_admin_v1_authentication_proto_goTypes,
		DependencyIndexes: file_api_authentication_admin_v1_authentication_proto_depIdxs,
		MessageInfos:      file_api_authentication_admin_v1_authentication_proto_msgTypes,
	}.Build()
	File_api_authentication_admin_v1_authentication_proto = out.File
	file_api_authentication_admin_v1_authentication_proto_rawDesc = nil
	file_api_authentication_admin_v1_authentication_proto_goTypes = nil
	file_api_authentication_admin_v1_authentication_proto_depIdxs = nil
}
